# Generated by Django 4.0.1 on 2022-01-30 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffinfo',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
