# Generated by Django 4.0.1 on 2022-01-30 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_alter_staffinfo_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffinfo',
            name='end_date',
            field=models.DateField(null=True),
        ),
    ]
